version: 2.1
workflows:
  main:
    jobs:
      - compile
      - build
jobs:
  compile:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
  steps:
    - checkout
    - run:
          # Update this line with the directory that contains your tests project file
          working_directory: ./aspnetapp/
          name: Compile
          command: |
            ls -altr
            pwd
            dotnet restore
            dotnet publish
  build:
    docker:
      - image: docker:17.05.0-ce-git
  steps:
    - checkout
    - run:
          # Update this line with the directory that contains your tests project file
          working_directory: ./aspnetapp/
          name: Build Docker image
          command: |
            ls -altr
            pwd
            docker  build -t tt1 . --no-cache
