version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

    steps:
      - checkout
      - run:
          working_directory: ./aspnetapp/
          name: Compile src
          command: |
            ls -altr
            pwd
            dotnet restore
            dotnet publish
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            ls -altr
            pwd
            docker  build -t tt1 . --no-cache
 